[font]
ttf_path = /usr/share/fonts/truetype/noto/NotoSans-Medium.ttf
em_height = 20
spread_pixels = 1.5

[output]
c_header = SDFLib/sdf_font.h
c_source = SDFLib/sdf_font.c
font_name = sdf_font

[characters]
# Digits, punctuation, needed uppercase initials, all lowercase, and localized accents
characters = 0123456789.:?'¿ADFGHJLMNOSTUVWZabcdefghijklmnopqrstuvwxyzäöüßåøæáéíóúñàèìòù
